var data = {
    '1': {
      question: 'GUESS the movie name?',
      "url":"qus-1-images/1.png",
      'opt1': 'kathi',
      'opt2': 'Thuppaki',
      'opt3': 'Theri',
      'opt4': 'kaavalan',
       'ans': '1',
    },
    '2': {
      question: 'GUESS the movie name?',
      "url":"qus-1-images/2.png",
      'opt1': 'kathi',
      'opt2': 'Master',
      'opt3': 'Theri',
      'opt4': 'kaavalan',
       'ans': '2',
    },
    '3': {
        question: 'GUESS the movie name?',
        "url":"qus-1-images/3.png",
        'opt1': 'Mersal',
        'opt2': 'Thuppaki',
        'opt3': 'Theri',
        'opt4': 'kaavalan',
         'ans': '1',
      },
      '4': {
        question: 'GUESS the movie name?',
        "url":"qus-1-images/4.png",
        'opt1': 'kathi',
        'opt2': 'Master',
        'opt3': 'Thuppaki',
        'opt4': 'kaavalan',
         'ans': '3',
      },
      '5': {
        question: 'GUESS the movie name?',
        "url":"qus-1-images/5.png",
        'opt1': 'Bigil',
        'opt2': 'Master',
        'opt3': 'Thuppaki',
        'opt4': 'kaavalan',
        
         'ans': '1',
      },
      '6': {
        question: 'GUESS the movie name?',
        "url":"qus-1-images/6.png",
        'opt1': 'Bigil',
        'opt2': 'Master',
        'opt3': 'Sarkar',
        'opt4': 'kathi',
         'ans': '3',
      },
      '7': {
        question: 'GUESS the movie name?',
        "url":"qus-1-images/7.png",
        'opt1': 'kathi',
        'opt2': 'Master',
        'opt3': 'Thuppaki',
        'opt4': 'Nanban',
         'ans': '4',
      },
      '8': {
        question: 'GUESS the movie name?',
        "url":"qus-1-images/8.png",
        'opt1': 'kathi',
        'opt2': 'Thuppaki',
        'opt3': 'Theri',
        'opt4': 'kaavalan',
        
         'ans': '3',
      },
      '9': {
        question: 'GUESS the movie name? ',
        "url":"qus-1-images/9.png",
        'opt1': 'puli',
        'opt2': 'Thuppaki',
        'opt3': 'Theri',
        'opt4': 'kaavalan',
         'ans': '1',
      }};